config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root "events#index"

  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]

    post :show, on: :member
  end

  resources :users, only: [:show, :edit, :update]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  belongs_to :user, optional: true

  validates :body, presence: true
  validates :user_name, presence: true, unless: -> { user.present? }

  def user_name
    user.present? ? user.name : super
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_event, only: [:create, :destroy]
  before_action :set_comment, only: [:destroy]

  def create
    @new_comment = @event.comments.build(comment_params)
    @new_comment.user = current_user

    if @new_comment.save
      notify_subscribers(@event, @new_comment)

      redirect_to @event, notice: I18n.t('controllers.comments.created')
    else
      render 'events/show', alert: I18n.t('controllers.comments.error')
    end
  end

  def destroy
    message = {notice: I18n.t('controllers.comments.destroyed')}

    if current_user_can_edit?(@comment)
      @comment.destroy!
    else
      message = {alert: I18n.t('controllers.comments.error')}
    end

    redirect_to @event, message
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_comment
    @comment = @event.comments.find(params[:id])

  end

  def comment_params
    params.require(:comment).permit(:body, :user_name)
  end

  def notify_subscribers(event, comment)
    all_emails = (event.subscriptions.map(&:user_email) + [event.user.email] - [comment.user&.email]).uniq
    all_emails.each do |mail|
      EventMailer.comment(comment, mail).deliver_now
    end
  end
end

app/views/comments/_comment.html.erb
<table class="table table-hover table-sm">
  <table class="table align-middle">
    <tbody>
    <tr>
      <td class="text-break"><%= comment.body %></td>

      <td>
        <% if comment.user.present? %>
          <%= render partial: 'users/user', object: comment.user %>
        <% else %>
          <em><strong><%= comment.user_name %></strong></em>
        <% end %>
      </td>

      <td><%= l comment.created_at, format: :short %></td>

      <td>
        <% if current_user_can_edit?(comment) %>
          <%= button_to t('. delete'), event_comment_path(comment.event, comment), method: :delete,
                        form: { data: { turbo_confirm: t('.destroy_confirm') } },
                        class: 'btn btn-danger' %>
        <% end %>
      </td>
    </tr>
    </tbody>
  </table>
</table>

app/views/comments/_form.html.erb
<%= form_for [@event, comment], data: { turbo: false } do |f| %>
    <%= render partial: 'partials/form_errors', locals: {errors: comment.errors} %>

    <div class="mt-3">
      <%= f.text_area :body, placeholder: true, class: 'form-control' %>
    </div>

    <% unless user_signed_in? %>
        <div class="mt-3">
          <%= f.text_field :user_name, placeholder: true, class: 'form-control' %>
        </div>
    <% end %>

    <div class="mt-3">
      <%= f.submit t('.send'), class: 'btn btn-success' %>
    </div>
<% end %>