config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root "events#index"

  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]

    post :show, on: :member
  end

  resources :users, only: [:show, :edit, :update]
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user

  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user
  has_many :photos, dependent: :destroy

  validates :user, presence: true
  validates :title, presence: true, length: {maximum: 255}
  validates :address, presence: true
  validates :datetime, presence: true

  def visitors
    (subscribers + [user]).uniq
  end

  def pincode_valid?(pin2check)
    pincode == pin2check
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_event, only: [:show]
  before_action :set_current_user_event, only: [:edit, :update, :destroy]
  before_action :password_guard!, only: [:show]

  def index
    @events = Event.all
  end

  def show
    @new_comment = @event.comments.build(params[:comment])
    @new_subscription = @event.subscriptions.build(params[:subscription])
    @new_photo = @event.photos.build(params[:photo])
  end

  def new
    @event = current_user.events.build
  end

  def edit
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      redirect_to @event, notice: I18n.t('controllers.events.created')
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: I18n.t('controllers.events.updated')
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url, notice: I18n.t('controllers.events.destroyed')
  end

  private

  def password_guard!
    return true if @event.pincode.blank?
    return true if signed_in? && current_user == @event_user

    if params[:pincode].present? && @event.pincode_valid?(params[:pincode])
      cookies.permanent["events_#{@event.id}_pincode"] = params[:pincode]
    end

    pincode = cookies.permanent["events_#{@event.id}_pincode"]
    unless @event.pincode_valid?(pincode)
      if params[:pincode].present?
        flash.now[:alert] = I18n.t('controllers.events.wrong_pincode')
      end
      render 'password_form'
    end
  end

  def set_current_user_event
    @event = current_user.events.find(params[:id])
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:title, :address, :datetime, :description, :pincode)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="col">
  <div class="card border-success border-2 mb-3 mt-5" style="max-width: 18rem;">
    <div class="card-header"><%= link_to event.title, event_path(event),
                                         class: 'nav-link link-success text-center text-uppercase' %></div>
    <div class="card-body">
      <p class="card-text"><%= event.description %></p>
      <p class="card-text"><%= l event.datetime, format: :short %></p>
      <p class="card-text"><%= event.address %></p>
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <% event.visitors.each do |user| %>
          <%= link_to image_tag(user_avatar(user), style: 'width: 30px', class: 'rounded-circle',
                        title: user.name), user_path(user) %>
        <% end %>
      </li>
    </ul>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_for event, data: { turbo: false } do |f| %>
  <%= render partial: 'partials/form_errors', locals: {errors: event.errors} %>

  <div class="mb-3 mt-2">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="mb-3">
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div>
    <%= f.label :datetime %>
    <p><%= f.datetime_select :datetime, class: 'form-control' %></p>
  </div>

  <div class="mb-3">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>

  <div>
    <%= f.label :pincode %>
    <%= f.text_field :pincode, class: 'form-control' %>
  </div>

  <div class="mt-4">
    <%= f.submit t('events.save'), class: 'btn btn-success' %>
    <%= t('events.or') %>
    <%= link_to t('events.back'), :back %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1 class="mt-3"><%= t('events.edit_event') %></h1>

<div class="row">
  <div class="col-md-8">
    <%= render 'form', event: @event %>
  </div>
</div>

app/views/events/index.html.erb
<h1 class="my-3"><%= t('events.all_events') %></h1>

<div>
  <%= link_to t('events.new_event'), new_event_path, class: 'btn btn-success' %>
</div>

<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4 g-4">
  <%= render partial: 'events/event', collection: @events %>
</div>

app/views/events/new.html.erb
<h1 class="mt-3"><%= t('events.new_event') %></h1>

<div class="row">
  <div class="col-md-8">
    <%= render 'form', event: @event %>
  </div>
</div>

app/views/events/password_form.html.erb
<h1 class="my-3"><%= t('events.pincode_access') %></h1>

<%= form_tag(event_path(@event), method: 'post', data: { turbo: false }) do |f| %>
  <div class="">
    <%= label :pincode, t('events.pincode') %>
    <%= text_field_tag :pincode, params[:pincode], class: 'form-control' %>
  </div>

  <div class="my-4">
    <%= submit_tag t('events.confirm'), class: 'btn btn-success' %>
  </div>
<% end %>

<%= link_to t('events.to_index'), events_path %>

app/views/events/show.html.erb
<div class="container my-3">
  <h1><%= @event.title %></h1>
  <h4><%= l @event.datetime, format: :short %></h4>
  <h3><small><%= link_to @event.address,
                         "https://yandex.ru/maps/?text=#{@event.address}",
                         class: '' %></small></h3>
  <p class="mt-3"><%= @event.description %></p>

  <% if current_user_can_edit?(@event) %>
    <div class="mt-4">
      <%= link_to t('events.edit'), edit_event_path(@event),
                  class: 'btn btn-success' %>
      <%= t('events.or') %>
      <%= link_to t('events.back'), :back %>
    </div>

    <div class="mt-4">
      <%= button_to t('events.delete_event'), event_path(@event),
                    method: :delete,
                    form: { data: { turbo_confirm: t('events.confirm_event') } },
                    class: 'btn btn-danger' %>
    </div>
  <% end %>
  <div id="map"
       data-address="<%= @event.address %>"
       style="width: 100%; height: 200px">
  </div>
</div>

<div class="row">
  <div class="col-md-8">
    <h3 class="text-center mt-3"><%= t('events.gallery') %></h3>
    <div class="row">
      <% unless @event.photos.except.present? %>
        <p class="text-muted text-center my-3"><%= t('events.no_photos') %></p>
      <% end %>
      <%= render partial: 'photos/photo', collection: @event.photos.except(@new_photo) %>
    </div>

    <% if user_signed_in? %>
      <div class="">
        <%= render partial: 'photos/form', locals: { photo: @new_photo || @event.photos.build } %>
      </div>
    <% end %>

    <div class="">
      <%= render partial: 'comments/form',
                 locals: { comment: @new_comment || @event.comments.build } %>

      <div class="my-3">
        <%= render partial: 'comments/comment',
                   collection: @event.comments.except(@new_comment) %>
      </div>
    </div>
  </div>

  <div class="col-md-4">
    <h4 class="text-white bg-dark text-center p-2 rounded-pill"><%= t('events.calling') %></h4>
    <p class="text-center"><%= render partial: 'users/user', object: @event.user %></p>

    <div class="">
      <h4 class="text-white bg-dark text-center p-2 rounded-pill"><%= t('events.going') %></h4>
      <div class="text-center">

        <% if @event.subscriptions.except(@new_subscription).empty? %>
          <p class="text-center text-muted"><%= t 'events.no_subscribers' %></p>
        <% end %>

        <p><%= render partial: 'subscriptions/subscription',
                      collection: @event.subscriptions.except(@new_subscription) %></p>
      </div>
    </div>
    <% unless current_user == @event.user %>
      <div class="mt-3">
        <h4 class="text-white bg-success text-center p-2 rounded-pill"><%= t('events.i_go') %></h4>
        <div>
          <%= render partial: 'subscriptions/form', locals: {
            subscription: @new_subscription || @event.subscriptions.build
          } %>
        </div>
      </div>
    <% end %>
  </div>
</div>