config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks'
  }

  root "events#index"

  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]

    post :show, on: :member
  end

  resources :users, only: [:show, :edit, :update]
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  EMAIL_REGEXP = /\A[a-zA-Z0-9\-_.]+@[a-zA-Z0-9\-_.]+\z/

  belongs_to :event
  belongs_to :user, optional: true

  with_options if: -> { user.present? } do
    validates :user, uniqueness: {scope: :event_id}
    validate :same_user
  end

  with_options unless: -> { user.present? } do
    validates :user_name, presence: true
    validates :user_email, presence: true, format: EMAIL_REGEXP
    validates :user_email, uniqueness: {scope: :event_id}
    validate :existing_email
  end

  def user_name
    user&.name || super
  end

  def user_email
    user&.email || super
  end

  private

  def same_user
    errors.add(:user_email, :same_user) if user == event.user
  end

  def existing_email
    errors.add(:user_email, :existing_email) if User.exists?(email: user_email)
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_event, only: [:create, :destroy]
  before_action :set_subscription, only: [:destroy]

  def create
    @new_subscription = @event.subscriptions.build(subscription_params)
    @new_subscription.user = current_user

    if @new_subscription.save
      EventMailer.subscription(@event, @new_subscription).deliver_now

      redirect_to @event, notice: I18n.t('controllers.subscriptions.created')
    else
      render 'events/show', alert: I18n.t('controllers.subscriptions.error')
    end
  end

  def destroy
    message = {notice: I18n.t('controllers.subscriptions.destroyed')}

    if current_user_can_edit?(@subscription)
      @subscription.destroy
    else
      message = {alert: I18n.t('controllers.subscriptions.error')}
    end

    redirect_to @event, message
  end

  private

  def set_subscription
    @subscription = @event.subscriptions.find(params[:id])
  end

  def set_event
    @event = Event.find(params[:event_id])
  end

  def subscription_params
    # .fetch разрешает в params отсутствие ключа :subscription
    params.fetch(:subscription, {}).permit(:user_email, :user_name)
  end
end

app/views/subscriptions/_form.html.erb
<%= form_for [@event, subscription], data: { turbo: false } do |f| %>
  <%= render partial: 'partials/form_errors', locals: { errors: subscription.errors } %>

  <% unless user_signed_in? %>
    <div class="mt-3">
      <%= f.text_field :user_name, placeholder: true, class: 'form-control' %>
    </div>

    <div class="mt-3">
      <%= f.text_field :user_email, placeholder: true, class: 'form-control' %>
    </div>
  <% end %>

  <div class="my-3">
    <%= f.submit t('.subscribe'), class: 'btn btn-success' %>
  </div>
<% end %>

app/views/subscriptions/_subscription.html.erb
<table class="table table-hover table-sm">
  <table class="table align-middle">
    <tbody>
    <tr>
      <% if subscription.user.present? %>
        <td><%= render partial: 'users/user', object: subscription.user %></td>
      <% else %>
        <td><%= subscription.user_name %></td>
      <% end %>
      <td>
      <% if current_user_can_edit?(subscription) %>
        <%= button_to t('.delete'), event_subscription_path(subscription.event, subscription), method: :delete,
                      form: { data: { turbo_confirm: t('.destroy_confirm') } },
                      class: 'btn btn-danger'%>
      <% end %>
      </td>
    </tr>
    </tbody>
  </table>
</table>